### ISSUE TITLE
Feature: Shell: Enable and Disable Simon Says Game

### ISSUE THREAD

**Issue by ubieda** [NickIOT72/SimonSaysApp_Zephyr#3]
By default, Simon Says is disabled, but you can enable it with Shell commands.

**Comment by ubieda** [comment]
@fabocode

**Comment by fabocode** [comment]
I made a branch to add this feature [feature/addShell](https://github.com/NickIOT72/SimonSaysApp_Zephyr/tree/feature/addShell) 

However, I am not sure where I should merge the PR, it would be better to create a PR to merge it into the master branch? or from the parent branch of the feature branch I created? (Which is `feature/addButtonModule`)
